# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ alpha ]
  pull_request:
    branches: [ alpha ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies and build app
      run: |
        npm ci
        npm run build
    - uses: actions/upload-artifact@v1
      name: Store build
      with:
        name: build-artifact
        path: build-artifact
        
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v1.0.0
      with:
        name: build-artifact
    - name: Run semantic release and publish new version to npm
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm run semantic-release
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v1.0.0
      with:
        name: build-artifact
    - name: Deploy docs to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.4.1
      with:
        ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: www # The folder the action should deploy.

