name: CI
on:
  push:
    branches: [ alpha ]
  pull_request:
    branches: [ alpha ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci

    - name: Build web component and documentation
      run: npm run build
   
    - name: Run semantic release and publish new version to npm
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm run semantic-release
    
    - name: Set base href
      run: npm run replace '<base href=(.*?)>' '<base href="/${{ github.event.repository.name }}/">' www/index.html
      
    - name: Deploy documentation to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.4.1
      with:
        ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: www # The folder the action should deploy.

