name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    
    - name: Get last version
      id: version
      uses: jessicalostinspace/github-action-get-regex-branch@v1.0.8
      with:
        regex-string: 'alpha'
    
    - name: Get last version
      run: echo "The time was ${{ steps.version.outputs.last-semver }}"  

    - name: Build web component and documentation
      run: npm run build
    
    - uses: codfish/semantic-release-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
   
    #- name: Run semantic release and publish new version to npm
    #  env:
    #    GH_TOKEN: ${{ secrets.GH_TOKEN }}
    #    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    #  run: npm run semantic-release
    
    - name: Set base href
      if: steps.semantic.outputs.new-release-published == 'true'
      run: ./node_modules/.bin/replace '<base href=(.*?)>' '<base href="/${{ github.event.repository.name }}/">' www/index.html
    
    - name: Set build (run) number
      if: steps.semantic.outputs.new-release-published == 'true'
      run: ./node_modules/.bin/replace '##BUILD_NUMBER##' '${{ github.run_number }}' www/index.html
    
    - name: Set version number
      if: steps.semantic.outputs.new-release-published == 'true'
      run: ./node_modules/.bin/replace '##VERSION##' '${{ steps.semantic.outputs.release-version }}' www/index.html
        
    - name: Deploy documentation to GitHub Pages
      if: steps.semantic.outputs.new-release-published == 'true'
      uses: JamesIves/github-pages-deploy-action@3.4.1
      with:
        ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: www # The folder the action should deploy.

